/*
 * Copyright (C) 2018-2025 Philip Helger (www.helger.com)
 * philip[at]helger[dot]com
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.helger.photon.bootstrap5.trait;

import org.jspecify.annotations.NonNull;
import org.jspecify.annotations.Nullable;

import com.helger.html.hc.IHCNode;
import com.helger.html.hc.html.traits.IHCTrait;
import com.helger.photon.bootstrap5.alert.BootstrapDangerBox;
import com.helger.photon.bootstrap5.alert.BootstrapErrorBox;
import com.helger.photon.bootstrap5.alert.BootstrapInfoBox;
import com.helger.photon.bootstrap5.alert.BootstrapQuestionBox;
import com.helger.photon.bootstrap5.alert.BootstrapSuccessBox;
import com.helger.photon.bootstrap5.alert.BootstrapWarnBox;
import com.helger.photon.bootstrap5.badge.BootstrapBadge;
import com.helger.photon.bootstrap5.badge.EBootstrapBadgeType;

/**
 * Traits interface to add simpler UI codes.<br>
 * Generated by MainCreateHCBootstrap5TraitsCode
 *
 * @author Philip Helger
 */
public interface IHCBootstrap5Trait extends IHCTrait
{
  @NonNull
  default BootstrapBadge badge ()
  {
    return new BootstrapBadge ();
  }

  @NonNull
  default BootstrapBadge badge (final int nValue)
  {
    return new BootstrapBadge ().addChild (Integer.toString (nValue));
  }

  @NonNull
  default BootstrapBadge badge (final long nValue)
  {
    return new BootstrapBadge ().addChild (Long.toString (nValue));
  }

  @NonNull
  default BootstrapBadge badge (@Nullable final IHCNode aNode)
  {
    return new BootstrapBadge ().addChild (aNode);
  }

  @NonNull
  default BootstrapBadge badge (@Nullable final String s)
  {
    return new BootstrapBadge ().addChild (s);
  }

  @NonNull
  default BootstrapBadge badge (@Nullable final Iterable <? extends IHCNode> aNodes)
  {
    return new BootstrapBadge ().addChildren (aNodes);
  }

  @NonNull
  default BootstrapBadge badge (@Nullable final String... aTexts)
  {
    return new BootstrapBadge ().addChildren (aTexts);
  }

  @NonNull
  default BootstrapBadge badgeDanger ()
  {
    return new BootstrapBadge (EBootstrapBadgeType.DANGER);
  }

  @NonNull
  default BootstrapBadge badgeDanger (final int nValue)
  {
    return new BootstrapBadge (EBootstrapBadgeType.DANGER).addChild (Integer.toString (nValue));
  }

  @NonNull
  default BootstrapBadge badgeDanger (final long nValue)
  {
    return new BootstrapBadge (EBootstrapBadgeType.DANGER).addChild (Long.toString (nValue));
  }

  @NonNull
  default BootstrapBadge badgeDanger (@Nullable final IHCNode aNode)
  {
    return new BootstrapBadge (EBootstrapBadgeType.DANGER).addChild (aNode);
  }

  @NonNull
  default BootstrapBadge badgeDanger (@Nullable final String s)
  {
    return new BootstrapBadge (EBootstrapBadgeType.DANGER).addChild (s);
  }

  @NonNull
  default BootstrapBadge badgeDanger (@Nullable final Iterable <? extends IHCNode> aNodes)
  {
    return new BootstrapBadge (EBootstrapBadgeType.DANGER).addChildren (aNodes);
  }

  @NonNull
  default BootstrapBadge badgeDanger (@Nullable final String... aTexts)
  {
    return new BootstrapBadge ().addChildren (aTexts);
  }

  @NonNull
  default BootstrapBadge badgeInfo ()
  {
    return new BootstrapBadge (EBootstrapBadgeType.INFO);
  }

  @NonNull
  default BootstrapBadge badgeInfo (final int nValue)
  {
    return new BootstrapBadge (EBootstrapBadgeType.INFO).addChild (Integer.toString (nValue));
  }

  @NonNull
  default BootstrapBadge badgeInfo (final long nValue)
  {
    return new BootstrapBadge (EBootstrapBadgeType.INFO).addChild (Long.toString (nValue));
  }

  @NonNull
  default BootstrapBadge badgeInfo (@Nullable final IHCNode aNode)
  {
    return new BootstrapBadge (EBootstrapBadgeType.INFO).addChild (aNode);
  }

  @NonNull
  default BootstrapBadge badgeInfo (@Nullable final String s)
  {
    return new BootstrapBadge (EBootstrapBadgeType.INFO).addChild (s);
  }

  @NonNull
  default BootstrapBadge badgeInfo (@Nullable final Iterable <? extends IHCNode> aNodes)
  {
    return new BootstrapBadge (EBootstrapBadgeType.INFO).addChildren (aNodes);
  }

  @NonNull
  default BootstrapBadge badgeInfo (@Nullable final String... aTexts)
  {
    return new BootstrapBadge ().addChildren (aTexts);
  }

  @NonNull
  default BootstrapBadge badgePrimary ()
  {
    return new BootstrapBadge (EBootstrapBadgeType.PRIMARY);
  }

  @NonNull
  default BootstrapBadge badgePrimary (final int nValue)
  {
    return new BootstrapBadge (EBootstrapBadgeType.PRIMARY).addChild (Integer.toString (nValue));
  }

  @NonNull
  default BootstrapBadge badgePrimary (final long nValue)
  {
    return new BootstrapBadge (EBootstrapBadgeType.PRIMARY).addChild (Long.toString (nValue));
  }

  @NonNull
  default BootstrapBadge badgePrimary (@Nullable final IHCNode aNode)
  {
    return new BootstrapBadge (EBootstrapBadgeType.PRIMARY).addChild (aNode);
  }

  @NonNull
  default BootstrapBadge badgePrimary (@Nullable final String s)
  {
    return new BootstrapBadge (EBootstrapBadgeType.PRIMARY).addChild (s);
  }

  @NonNull
  default BootstrapBadge badgePrimary (@Nullable final Iterable <? extends IHCNode> aNodes)
  {
    return new BootstrapBadge (EBootstrapBadgeType.PRIMARY).addChildren (aNodes);
  }

  @NonNull
  default BootstrapBadge badgePrimary (@Nullable final String... aTexts)
  {
    return new BootstrapBadge ().addChildren (aTexts);
  }

  @NonNull
  default BootstrapBadge badgeSuccess ()
  {
    return new BootstrapBadge (EBootstrapBadgeType.SUCCESS);
  }

  @NonNull
  default BootstrapBadge badgeSuccess (final int nValue)
  {
    return new BootstrapBadge (EBootstrapBadgeType.SUCCESS).addChild (Integer.toString (nValue));
  }

  @NonNull
  default BootstrapBadge badgeSuccess (final long nValue)
  {
    return new BootstrapBadge (EBootstrapBadgeType.SUCCESS).addChild (Long.toString (nValue));
  }

  @NonNull
  default BootstrapBadge badgeSuccess (@Nullable final IHCNode aNode)
  {
    return new BootstrapBadge (EBootstrapBadgeType.SUCCESS).addChild (aNode);
  }

  @NonNull
  default BootstrapBadge badgeSuccess (@Nullable final String s)
  {
    return new BootstrapBadge (EBootstrapBadgeType.SUCCESS).addChild (s);
  }

  @NonNull
  default BootstrapBadge badgeSuccess (@Nullable final Iterable <? extends IHCNode> aNodes)
  {
    return new BootstrapBadge (EBootstrapBadgeType.SUCCESS).addChildren (aNodes);
  }

  @NonNull
  default BootstrapBadge badgeSuccess (@Nullable final String... aTexts)
  {
    return new BootstrapBadge ().addChildren (aTexts);
  }

  @NonNull
  default BootstrapBadge badgeWarn ()
  {
    return new BootstrapBadge (EBootstrapBadgeType.WARNING);
  }

  @NonNull
  default BootstrapBadge badgeWarn (final int nValue)
  {
    return new BootstrapBadge (EBootstrapBadgeType.WARNING).addChild (Integer.toString (nValue));
  }

  @NonNull
  default BootstrapBadge badgeWarn (final long nValue)
  {
    return new BootstrapBadge (EBootstrapBadgeType.WARNING).addChild (Long.toString (nValue));
  }

  @NonNull
  default BootstrapBadge badgeWarn (@Nullable final IHCNode aNode)
  {
    return new BootstrapBadge (EBootstrapBadgeType.WARNING).addChild (aNode);
  }

  @NonNull
  default BootstrapBadge badgeWarn (@Nullable final String s)
  {
    return new BootstrapBadge (EBootstrapBadgeType.WARNING).addChild (s);
  }

  @NonNull
  default BootstrapBadge badgeWarn (@Nullable final Iterable <? extends IHCNode> aNodes)
  {
    return new BootstrapBadge (EBootstrapBadgeType.WARNING).addChildren (aNodes);
  }

  @NonNull
  default BootstrapBadge badgeWarn (@Nullable final String... aTexts)
  {
    return new BootstrapBadge ().addChildren (aTexts);
  }

  @NonNull
  default BootstrapDangerBox danger ()
  {
    return new BootstrapDangerBox ();
  }

  @NonNull
  default BootstrapDangerBox danger (@Nullable final IHCNode aNode)
  {
    return new BootstrapDangerBox ().addChild (aNode);
  }

  @NonNull
  default BootstrapDangerBox danger (@Nullable final String s)
  {
    return new BootstrapDangerBox ().addChild (s);
  }

  @NonNull
  default BootstrapDangerBox danger (@Nullable final Iterable <? extends IHCNode> aNodes)
  {
    return new BootstrapDangerBox ().addChildren (aNodes);
  }

  @NonNull
  default BootstrapDangerBox danger (@Nullable final String... aTexts)
  {
    return new BootstrapDangerBox ().addChildren (aTexts);
  }

  @NonNull
  default BootstrapErrorBox error ()
  {
    return new BootstrapErrorBox ();
  }

  @NonNull
  default BootstrapErrorBox error (@Nullable final IHCNode aNode)
  {
    return new BootstrapErrorBox ().addChild (aNode);
  }

  @NonNull
  default BootstrapErrorBox error (@Nullable final String s)
  {
    return new BootstrapErrorBox ().addChild (s);
  }

  @NonNull
  default BootstrapErrorBox error (@Nullable final Iterable <? extends IHCNode> aNodes)
  {
    return new BootstrapErrorBox ().addChildren (aNodes);
  }

  @NonNull
  default BootstrapErrorBox error (@Nullable final String... aTexts)
  {
    return new BootstrapErrorBox ().addChildren (aTexts);
  }

  @NonNull
  default BootstrapInfoBox info ()
  {
    return new BootstrapInfoBox ();
  }

  @NonNull
  default BootstrapInfoBox info (@Nullable final IHCNode aNode)
  {
    return new BootstrapInfoBox ().addChild (aNode);
  }

  @NonNull
  default BootstrapInfoBox info (@Nullable final String s)
  {
    return new BootstrapInfoBox ().addChild (s);
  }

  @NonNull
  default BootstrapInfoBox info (@Nullable final Iterable <? extends IHCNode> aNodes)
  {
    return new BootstrapInfoBox ().addChildren (aNodes);
  }

  @NonNull
  default BootstrapInfoBox info (@Nullable final String... aTexts)
  {
    return new BootstrapInfoBox ().addChildren (aTexts);
  }

  @NonNull
  default BootstrapQuestionBox question ()
  {
    return new BootstrapQuestionBox ();
  }

  @NonNull
  default BootstrapQuestionBox question (@Nullable final IHCNode aNode)
  {
    return new BootstrapQuestionBox ().addChild (aNode);
  }

  @NonNull
  default BootstrapQuestionBox question (@Nullable final String s)
  {
    return new BootstrapQuestionBox ().addChild (s);
  }

  @NonNull
  default BootstrapQuestionBox question (@Nullable final Iterable <? extends IHCNode> aNodes)
  {
    return new BootstrapQuestionBox ().addChildren (aNodes);
  }

  @NonNull
  default BootstrapQuestionBox question (@Nullable final String... aTexts)
  {
    return new BootstrapQuestionBox ().addChildren (aTexts);
  }

  @NonNull
  default BootstrapSuccessBox success ()
  {
    return new BootstrapSuccessBox ();
  }

  @NonNull
  default BootstrapSuccessBox success (@Nullable final IHCNode aNode)
  {
    return new BootstrapSuccessBox ().addChild (aNode);
  }

  @NonNull
  default BootstrapSuccessBox success (@Nullable final String s)
  {
    return new BootstrapSuccessBox ().addChild (s);
  }

  @NonNull
  default BootstrapSuccessBox success (@Nullable final Iterable <? extends IHCNode> aNodes)
  {
    return new BootstrapSuccessBox ().addChildren (aNodes);
  }

  @NonNull
  default BootstrapSuccessBox success (@Nullable final String... aTexts)
  {
    return new BootstrapSuccessBox ().addChildren (aTexts);
  }

  @NonNull
  default BootstrapWarnBox warn ()
  {
    return new BootstrapWarnBox ();
  }

  @NonNull
  default BootstrapWarnBox warn (@Nullable final IHCNode aNode)
  {
    return new BootstrapWarnBox ().addChild (aNode);
  }

  @NonNull
  default BootstrapWarnBox warn (@Nullable final String s)
  {
    return new BootstrapWarnBox ().addChild (s);
  }

  @NonNull
  default BootstrapWarnBox warn (@Nullable final Iterable <? extends IHCNode> aNodes)
  {
    return new BootstrapWarnBox ().addChildren (aNodes);
  }

  @NonNull
  default BootstrapWarnBox warn (@Nullable final String... aTexts)
  {
    return new BootstrapWarnBox ().addChildren (aTexts);
  }
}
